### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by expede**
- `fill the miss` is nonsensical. At very least I've never heard this phrase.
- `fix the mess` is the most logical, based on intent. Seems a bit harsh, perhaps?

### CODE REVIEW

**Comment by onebree** [comment]
@expede Feel free to completely change the whole paragraph. I agree that is sounds awkward overall. Maybe something along the lines of "takes the best advice from the best guides?"

**If** you know other languages, please translate those pages as well.

**Comment by kroehre** [comment]
@expede "fill the gap" seems like the intended phrase to me.

**Comment by onebree** [comment]
@kroehre :+1: I agree.

@expede, I suggest using `fill the gap`.

**Comment by expede** [comment]
Sorry for the delay! Updated to the suggested wording :smile:

**Comment by onebree** [comment]
@expede no need to apologize. This repository has been dormant lately, and everyone just needs to be reminded it's back and ready to go! I am merging your PR now. :-)

**Pull request merged**
