### PR TITLE
Prefer eq matcher than equal

### PR DESCRIPTION
**Pull request by rhannequin**
Initial PR is https://github.com/betterspecs/betterspecs/pull/200 but the project architecture changed in the mean time and the PR was never updated and able to be merged.

All credits to this contribution comes to @kachick who originally suggested this change.

### CODE REVIEW

**Comment by kachick** [comment]
Thank you!

**Review by kbrock — APPROVED** [review]
since we want equal value (i.e.: `eq`)and not equal object_id (i.e.: `equal`), `eq` is the way to go.

Of course, with ruby, all integers have the same object id - so both will work. But this new way is more semantically correct.

**Comment by rhannequin** [comment]
Shall we merge it? :)

**Review by kachick — APPROVED** [review]
LGTM 😄  (Sorry, I'm not a member of this repository 😄 )

**Comment by akz92** [comment]
yes! Thank you @rhannequin

**Comment by rhannequin** [comment]
And thanks to @kachick, who did all the work a while ago 😉 👏

**Pull request merged**
