### PR TITLE
Fix 'RSpec' capitalization

### PR DESCRIPTION
**Pull request by andyw8**

### CODE REVIEW

**Comment by onebree** [comment]
@andyw8 I did not catch this in a previously-accepted pull request (#133). Please pull from master into your branch, and make the change. I will gladly give you credit, rather than me making the commit!

Also, when you do this, squash your commits if possible. Thank you

**Comment by andyw8** [comment]
Thanks, I've updated it.

**Comment by onebree** [comment]
I am holding this PR until we reinstate the "Resources" section of the website.

**Comment by akz92** [comment]
Closing this as we're only making changes to the new `gh-pages` branch.

**Pull request closed without merging**
