### PR TITLE
Remove Gemcutter reference

### PR DESCRIPTION
**Pull request by andyw8**

### CODE REVIEW

**Comment by onebree** [comment]
@andyw8 Could you explain the `gemcutter` reference? I am all for using RubyGems instead, since it is the standard now. Was GemCutter the previous standard?

**Comment by andyw8** [comment]
I don't recall the full history, but I believe Gemcutter became Rubygems.org:
http://ruby.dzone.com/articles/new-rubygemsorg-gemcutter-and

**Comment by onebree** [comment]
Also, why change to HTTPS? Is there a difference obtaining the gems that way?

**Comment by philoserf** [comment]
It is https because that is the canonical URL for RubyGems source. Try a `bundle init`. That give a barebones canonical Gemfile. http://bundler.io/v1.9/gemfile.html

**Comment by onebree** [comment]
I am going to wait on merging this, until I learn more about this app's deployment. I want to make sure this change is successful. (I am sure it will be, thought)

**Review by kbrock — APPROVED** [review]
This has been best practice for a while

**Comment by kbrock** [comment]
`gemcutter.org` is deprecated and redirects to `rubygems.org`

```bash
# wget http://gemcutter.org
--2019-10-02 14:30:00--  http://gemcutter.org/
Resolving gemcutter.org (gemcutter.org)... 151.101.192.70, 151.101.64.70, 151.101.0.70, ...
Connecting to gemcutter.org (gemcutter.org)|151.101.192.70|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://rubygems.org [following]
--2019-10-02 14:30:00--  https://rubygems.org/
Resolving rubygems.org (rubygems.org)... 151.101.0.70, 151.101.192.70, 151.101.64.70, ...
Connecting to rubygems.org (rubygems.org)|151.101.0.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’
```

**Comment by akz92** [comment]
Closing this as we're only making changes to the new `gh-pages` branch.

**Pull request closed without merging**
