### PR TITLE
Update Rails Test Prescriptions link to latest edition

### PR DESCRIPTION
**Pull request by andyw8**
I'm currently unable to run the site locally to verify this looks correct (due to the old version of EventMachine of event machine not compiling on the latest OS X), so please verify this before merging.

I've included the full-size version of the image, since the other images have this, even thought it doesn't  seem to be used anywhere on the site. It's useful to have if there's ever a need to generate thumbnails of a different size.

### CODE REVIEW

**Comment by onebree** [comment]
Once we make updates to the content, like adding overall Rails 4 content and RSpec 3 content, I will accept this PR. The site right now is aimed at Rails3 and RSpec2, so I do not want o create any confusion right now.

**Comment by andyw8** [comment]
Makes sense. What do you think about adding a banner to the top of the site stating this, until an updated version is released?

**Comment by onebree** [comment]
I think that is a great idea! My idea for the site is to eventually make is a Github Pages repository, making edits a lot easier. (Using Jekyll, you can create content with Markdown.)

**Comment by onebree** [comment]
If you would like to add a new PR with this banner, please do so. I would like the banner to include:
- Current Rails/RSpec versions
- Versions that the site currently focuses on
- Clicking the banner brings up a changelog of RSpec 2.x to 3.x

**Comment by onebree** [comment]
@andyw8 I will be pushing this PR and others to the gh-pages branch over the weekend. I noticed that the links provided include additional parameters. I would prefer if you edit those parameters out; however, if you do not get to it by the weekend, I will do it for you :-)

**Comment by andyw8** [comment]
I left the existing params alone because I assume someone is receiving affiliate commission when a book is bought through one of the links. Do you think they should be removed?

**Comment by onebree** [comment]
@andreareginato do you want to keep these affiliate links, or strip all the extra parameters?

**Comment by andreareginato** [comment]
All advertising/affiliate links can be removed. Lets keep only the content and clean things up

**Comment by akz92** [comment]
Closing this as we're only making changes to the new gh-pages branch.

**Pull request closed without merging**
