### PR TITLE
Fixed tweet typo and menu bar for jp.html.

### PR DESCRIPTION
**Pull request by Kakakakakku**
I fixed typo for jp.html, especially `partials/share`.
Thank you :+1:

### CODE REVIEW

**Comment by onebree** [comment]
@Kakakakakku Hello. Since you are editing the same file, could you make a second commit in this pull request, but add the changes from #149?

**Comment by Kakakakakku** [comment]
@onebree 
Sure, and I did it.
Is this ok?
So, I will close PR #149.

**Comment by onebree** [comment]
That is great! Thank you. This prevents an extra merge commit, making the history look nicer.

**Comment by Kakakakakku** [comment]
yes, that's right.
thanks :+1: 
>making the history look nicer.

**Pull request merged**
