### PR TITLE
Update thoughtbot related reading

### PR DESCRIPTION
**Pull request by franzejr**

### CODE REVIEW

**Comment by onebree** [comment]
@franzejr thank you! Looks good to me, so let me merge it. :-) Nice catch.

**Comment by franzejr** [comment]
@onebree, I just saw that Bitfluxx Best Practices is not working. Should we remove that from links, I didn't find another good link for this. Thanks

**Comment by onebree** [comment]
@franzejr let me look into the link. I will get back to you if it's worth it. :-)

**Comment by onebree** [comment]
@franzejr I found the link on the author's github repo. Please submit a pull request for the following:

https://github.com/Fluxx/bitfluxx.com/blob/master/_posts/2011-05-23-some-rspec-tips-and-best-practices.textile

**Pull request merged**
