### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by takiy33**

### CODE REVIEW

**Comment by onebree** [comment]
@takiy33 Could you explain the typo? I cannot read that language. Github only highlights a removed period as a change.

I will take this PR into consideration, depending on the change made, BUT in the future we will be editing the Spork section, and adding Spring.

**Comment by takiy33** [comment]
@onebree It is because that this line includes tow periods.
Japanese period is ”。” .

**Comment by onebree** [comment]
Okay. I am going to merge this immediately, since it is a translation page, and not additional rules or such.

**Comment by onebree** [comment]
Okay, I am going to label this as UPCOMING, as we need to figure out release and merge schedules for the site.

**Pull request merged**
